### PR TITLE
Update EMNLP 2020 papers

### PR DESCRIPTION
**Pull request by boxin-wbx**

### CODE REVIEW

**Review by yangalan123 — APPROVED** [review]
Thanks a lot! Although BERT-ATTACK (more knowledge-driven) and BAE (more data-driven) seem really similar in terms of the proposed methodology, considering they are both accepted to EMNLP 2020, we can just merge them into our list and leave the citing decision to the researchers using our list. It is also interesting to compare similar work.

**Comment by shizhouxing** [comment]
Hi @yangalan123, would you mind also adding this finding paper:

Robustness to Modification with Shared Words in Paraphrase Identification. Zhouxing Shi and Minlie Huang.

There was already an arxiv version in Sept 2019, which included leveraging masked language model for generating substitution words in adversarial examples, while this alone seems to be the core method in later BERT-ATTACK and BAE.

**Comment by yangalan123** [comment]
From my personal perspective, I do not want to discuss the originality of the accepted papers in this repo -- this repo only serves as a paper list, not a review forum like OpenReview. The paper you listed seems eligible for adding to our list, but I am not sure whether I should add to the list three papers that have a lot in common. @Fanchao-Qi @zangy17 What do you think about it?

**Comment by shizhouxing** [comment]
@yangalan123  Yes, actually I don't intend to raise discussions on paper originality here, but I just hope this paper had better not been missed in the list while the other two are added.

**Comment by yangalan123** [comment]
Can you help raise a Pull Request so we can continue our discussion there? My current attitude agree with you but I think for this case I need to discuss with other major contributors.

**Comment by shizhouxing** [comment]
@yangalan123 Sure. Pull request opened [here](https://github.com/thunlp/TAADpapers/pull/14). Also adding an ACL 2019 paper by the way.

**Pull request merged**
