### PR TITLE
add related papers at ACL'22

### PR DESCRIPTION
**Pull request by lethaiq**
Thank you in advance!

### CODE REVIEW

**Comment by yangalan123** [comment]
Hi, thanks for your PR! I have checked your PR and I think it is good to merge. Sorry for the late reply as we are busy with some other work. Good works!

**Comment by lethaiq** [comment]
thank a lot!

**Comment by lethaiq** [comment]
I don't think I have write access to the repo. Can you help me merge it?

**Comment by yangalan123** [comment]
Sure! I can help merge it. I also had some problem with write access but now solved lol.

**Comment by lethaiq** [comment]
Thank you!

**Pull request merged**
