### PR TITLE
add new paper

### PR DESCRIPTION
**Pull request by lethaiq**
Thanks

### CODE REVIEW

**Comment by yangalan123** [comment]
Sorry for the late reply since we are a bit busy with conference deadlines. Will check and merge later in Feb!

**Comment by lethaiq** [comment]
> Sorry for the late reply since we are a bit busy with conference deadlines. Will check and merge later in Feb!

Thanks!

**Comment by yangalan123** [comment]
Hi, we have merged your PR in the most recent commit and add you to our acknowledgment section. Thanks for your contribution! If you spot any problem, please follow-up in this thread.

**Comment by lethaiq** [comment]
> Hi, we have merged your PR in the most recent commit and add you to our acknowledgment section. Thanks for your contribution! If you spot any problem, please follow-up in this thread.

thanks!

**Pull request closed without merging**
